/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-10-09 07:03:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;

public final class formUpLoadDiem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/admin/Desktop/WorkSpaceM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Toolpdt/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1630768696582L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/Desktop/WorkSpaceM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Toolpdt/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Sắp xếp lịch thi</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./views/assets/upLoadDiem.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./views/assets/base.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./views/assets/grid.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\"\r\n");
      out.write("\tintegrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"app\">\r\n");
      out.write("\t\t<header class=\"header\">\r\n");
      out.write("\t\t\t<div class=\"grid wide\">\r\n");
      out.write("\t\t\t\t<img class=\"header_img\" src=\"./views/assets/image/Poly.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t<img class=\"header_icon_user\" src=\"./views/assets/image/user.png\"\r\n");
      out.write("\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t<button class=\"header_right-btn_user\">Đăng xuất</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"col container_middle\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"h1 container_header\">UPLOAD FILE ĐIỂM</h1>\r\n");
      out.write("\t\t\t\t\t");

					try{
						int data = Integer.parseInt(session.getAttribute("value").toString());
						if((data == 1) || (data == 2) || (data == 3)){
							out.print("<div class=\"container_alert\">\r\n"
									+ "							<div class=\"alert alert-danger container_alert-popup\"\r\n"
									+ "								role=\"alert\">Xin mời chọn file</div>\r\n"
									+ "						</div>");
						} else if(data == 5){
							out.print("<div class=\"container_alert\">\r\n"
									+ "							<div class=\"alert alert-danger container_alert-popup\"\r\n"
									+ "								role=\"alert\">Không phải định dạng file điểm Online, hãy thử lại</div>\r\n"
									+ "						</div>");
						} else if(data == 6){
							out.print("<div class=\"container_alert\">\r\n"
									+ "							<div class=\"alert alert-danger container_alert-popup\"\r\n"
									+ "								role=\"alert\">Không phải định dạng file điểm danh, hãy thử lại</div>\r\n"
									+ "						</div>");
						} else if(data == 7){
							out.print("<div class=\"container_alert\">\r\n"
									+ "							<div class=\"alert alert-danger container_alert-popup\"\r\n"
									+ "								role=\"alert\">Không phải định dạng file điểm Quiz, hãy thử lại</div>\r\n"
									+ "						</div>");
						} else if(data == 8){
							out.print("<div class=\"container_alert\">\r\n"
									+ "							<div class=\"alert alert-danger container_alert-popup\"\r\n"
									+ "								role=\"alert\">Lớp và Môn học không tồn tại trong kế hoạch thi kì này</div>\r\n"
									+ "						</div>");
						} else if(data == 9){
							out.print("<div class=\"container_alert\">\r\n"
									+ "							<div class=\"alert alert-danger container_alert-popup\"\r\n"
									+ "								role=\"alert\">File không hợp lệ</div>\r\n"
									+ "						</div>");
						}
					} catch(Exception e){
					}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<form action=\"/Toolpdt/Readlsistmark\" enctype=\"multipart/form-data\"\r\n");
      out.write("\t\t\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container_body\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container_body-button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"file\" id=\"UploadFileInput\" class=\"btnFile\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonchange=\"return fileValidation()\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container_body-cbb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"rdo-group \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"form-check-input\" type=\"radio\" name=\"Category\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"mark_quiz\" value=\"option1\" checked> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-check-label\" for=\"Category\">ĐIỂM QUIZ</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"form-check-input\" type=\"radio\" name=\"Category\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"mark_online\" value=\"option2\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-check-label\" for=\"Category\">ĐIỂM ONLINE</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"form-check-input\" type=\"radio\" name=\"Category\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"attendance\" value=\"option3\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-check-label\" for=\"Category\">ĐIỂM DANH</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"formDownLoad\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"textDownload\">Lựa chọn định dạng file muốn tải:</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"rdo-group_download\" id=\"modalCBB\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-check-input\" type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"downloadFile\" id=\"inlineRadio1\" value=\"fileExcel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tchecked> <label class=\"form-check-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfor=\"inlineRadio1\">DOWNLOAD FILE EXCEL</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-check-input\" type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"downloadFile\" id=\"inlineRadio2\" value=\"fileWord\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-check-label\" for=\"inlineRadio2\">DOWNLOAD\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tFILE WORD</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container_body-submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button formaction=\"/Toolpdt/Readlsistmark\" class=\"btn_submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"GFG_Fun()\">SUBMIT</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"container_footer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container_footer-download\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"./views/assets/image/241315670_374048297772326_2602951087702346768_n.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction fileValidation() {\r\n");
      out.write("\t\t\tvar fileInput = document.getElementById('UploadFileInput');\r\n");
      out.write("\t\t\tvar filePath = fileInput.value;\r\n");
      out.write("\t\t\tvar allowedExtendsion = /(\\.xls|\\.xlsx)$/i;\r\n");
      out.write("\r\n");
      out.write("\t\t\t// kiểm tra định dạng\r\n");
      out.write("\t\t\tif (!allowedExtendsion.exec(filePath)) {\r\n");
      out.write("\t\t\t\talert('Vui lòng chỉ upload file Excel!');\r\n");
      out.write("\t\t\t\tfileInput.value = '';\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar file = document.getElementById(\"UploadFileInput\");\r\n");
      out.write("\t\tfunction GFG_Fun() {\r\n");
      out.write("\t\t\tif (file.files.length == 0) {\r\n");
      out.write("\t\t\t\talert('Bạn chưa upload file!');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
