/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-10-08 04:53:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loadToUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Update Form</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"./views/assets/base.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"./views/assets/grid.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"./views/assets/loadToUpdate.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"./views/assets/fontawesome-free-5.15.3-web/css/all.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\"\n");
      out.write("        integrity=\"sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l\" crossorigin=\"anonymous\">\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"\n");
      out.write("        integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\"\n");
      out.write("        crossorigin=\"anonymous\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <div id=\"app\">\n");
      out.write("        <header class=\"header\">\n");
      out.write("            <div class=\"grid wide\">\n");
      out.write("                <a href=\"HomeForm.html\"><img class=\"header_img\" src=\"./views/assets/image/Poly.png\" alt=\"HomeForm.html\"></a>\n");
      out.write("                <img class=\"header_icon_user\" src=\"./views/assets/image/user.png\" alt=\"\">\n");
      out.write("                <button class=\"header_right-btn_user\">Đăng xuất</button>\n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"title\">\n");
      out.write("                <h2>>> UPDATE KẾ HOẠCH THI</h2>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <form action=\"updatekht\" method=\"post\">\n");
      out.write("            \t<div class=\"mb-3 row\">\n");
      out.write("                    <p for=\"staticEmail\" class=\"col-sm-4 label_text col-form-label\">ID Kế hoạch thi</p>\n");
      out.write("                    <div class=\"col-sm-7\">\n");
      out.write("                        <input type=\"text\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name = \"idkht\" class=\"form-control input_control\" id=\"inputPassword\" readonly>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mb-3 row\">\n");
      out.write("                    <p for=\"staticEmail\" class=\"col-sm-4 label_text col-form-label\">Ngày thi</p>\n");
      out.write("                    <div class=\"col-sm-7\">\n");
      out.write("                        <input type=\"date\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.ngayThi }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name = \"ngay\" class=\"form-control input_control\" id=\"inputPassword\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mb-3 row\">\n");
      out.write("                    <p for=\"inputPassword\" class=\"col-sm-4 label_text col-form-label\">Ca thi</p>\n");
      out.write("                    <div class=\"col-sm-7\">\n");
      out.write("                        <input type=\"text\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.caThi }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name = \"caThi\" class=\"form-control input_control\" id=\"cathi\" onchange=\"checkForm()\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mb-3 row\">\n");
      out.write("                    <p for=\"staticEmail\" class=\"col-sm-4 label_text col-form-label\">Phòng thi</p>\n");
      out.write("                    <div class=\"col-sm-7\">\n");
      out.write("                        <input type=\"text\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.phongThi }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name = \"phongThi\" class=\"form-control input_control\" id=\"inputPassword\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mb-3 row\">\n");
      out.write("                    <p for=\"inputPassword\" class=\"col-sm-4 label_text col-form-label\">Tên môn</p>\n");
      out.write("                    <div class=\"col-sm-7\">\n");
      out.write("                        <input type=\"text\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.tenMon }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name = \"tenMon\" class=\"form-control input_control\" id=\"inputPassword\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mb-3 row\">\n");
      out.write("                    <p for=\"staticEmail\" class=\"col-sm-4 label_text col-form-label\">Mã môn</p>\n");
      out.write("                    <div class=\"col-sm-7\">\n");
      out.write("                        <input type=\"text\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.maMon }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name = \"maMon\" class=\"form-control input_control\" id=\"inputPassword\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mb-3 row\">\n");
      out.write("                    <p for=\"inputPassword\" class=\"col-sm-4 label_text col-form-label\">Loại thi</p>\n");
      out.write("                    <div class=\"col-sm-7\">\n");
      out.write("                        <input type=\"text\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.loaiThi }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name = \"loaiThi\" class=\"form-control input_control\" id=\"inputPassword\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mb-3 row\">\n");
      out.write("                    <p for=\"staticEmail\" class=\"col-sm-4 label_text col-form-label\">Giáo viên</p>\n");
      out.write("                    <div class=\"col-sm-7\">\n");
      out.write("                        <input type=\"text\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.giangVien }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name = \"giangVien\" class=\"form-control input_control\" id=\"inputPassword\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mb-3 row\">\n");
      out.write("                    <p for=\"inputPassword\" class=\"col-sm-4 label_text col-form-label\">Lớp</p>\n");
      out.write("                    <div class=\"col-sm-7\">\n");
      out.write("                        <input type=\"text\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.lop }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name = \"lop\" class=\"form-control input_control\" id=\"inputPassword\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <input type=\"submit\" class=\"btn btn-success update_btn\" value = \"UPDATE\" >\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("    \t\n");
      out.write("        function checkForm() {\n");
      out.write("            var cathi = document.getElementById('cathi').value;\n");
      out.write("\n");
      out.write("            if (isNaN(cathi)) {\n");
      out.write("                document.getElementById('cathi').style.borderColor = \"red\";\n");
      out.write("                alert(\"Value input Ca thi not a number, Please try again!\");\n");
      out.write("            } else {\n");
      out.write("                if (cathi <=6 && cathi >=1) {\n");
      out.write("                    document.getElementById('cathi').style.borderColor = \"green\";\n");
      out.write("                } else {\n");
      out.write("                    document.getElementById('cathi').style.borderColor = \"red\";\n");
      out.write("                    alert(\"Value input Ca thi must between 1 to 6, Please try again!\");\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
